{{- range $name, $secret := .Values.vault.secrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secret.staticSecretRef }}
  labels:
    {{- include "bender.labels" $ | nindent 4 }}
spec:
  vaultAuthRef: {{ $.Values.vault.authRef }}
  type: kv-v2
  mount: {{ $secret.mount }}
  path: {{ $secret.path }}
  refreshAfter: {{ $secret.refreshAfter }}
  destination:
    name: {{ $secret.destinationSecretName }}
    create: true
---
{{- end }}
